// <auto-generated />
namespace URLShortner.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changedtolongdatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtolongdatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "202307261637389_changed to long datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
